Repository AY2324S2-CS2103T-T15-1/tp, pull requests merged in 2024-03, with the labels that each got.

#30 added updated UI
  docs/images/Ui.png
Labels: priority.high

#41 updated DG product scope
  docs/DeveloperGuide.md
Labels: priority.high

#51 [Internal Feat] Find person by nric
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: priority.high

#50 Add appointment to MediCLI
  src/main/java/seedu/address/commons/util/IdUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentDate.java
  src/main/java/seedu/address/model/appointment/AppointmentId.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/model/appointment/exceptions/InvalidAppointmentException.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/AppointmentListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/AppointmentListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/IdUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/appointment/AppointmentDateTest.java
  src/test/java/seedu/address/model/appointment/AppointmentIdTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundExceptionTest.java
  src/test/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentExceptionTest.java
  src/test/java/seedu/address/model/appointment/exceptions/InvalidAppointmentExceptionTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.story, priority.high

#63 Update promosed undo/redo feature UML diagrams and DG
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: priority.high, type.task

#64 Update DG description and class diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/ModelClassDiagramHandDrawn.png
Labels: priority.high, type.task

#69 Update main window title
  src/main/resources/view/MainWindow.fxml
Labels: priority.high, type.task

#76 Change UML diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: priority.high

#81 Query appointment by doctor
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/QueryDoctorAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/QueryDoctorAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/AppointmentContainsDoctorPredicate.java
  src/test/java/seedu/address/logic/commands/QueryDoctorAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/QueryDoctorAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentContainsDoctorPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: type.story, priority.medium

#83 add query person by expanded fields
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/QueryDoctorCommand.java
  src/main/java/seedu/address/logic/commands/QueryPatientCommand.java
  src/main/java/seedu/address/logic/parser/QueryDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/QueryPatientCommandParser.java
  src/main/java/seedu/address/model/person/DoctorContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PatientContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/QueryDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/QueryPatientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/QueryDoctorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/QueryPatientCommandParserTest.java
  src/test/java/seedu/address/model/person/DoctorContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/DoctorNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PatientContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PatientNameContainsKeywordsPredicateTest.java
Labels: priority.low, type.task

#86 Implement editappt
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.story, priority.medium

#89 Update DG with adddoctor and delete commands
  docs/DeveloperGuide.md
  docs/diagrams/AddDoctorActivityDiagram.puml
  docs/diagrams/DeletePersonActivityDiagram.puml
  docs/images/AddDoctorActivityDiagram.png
  docs/images/DeletePersonActivityDiagram.png
Labels: priority.high, type.task

#91 Improve appointment card
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/resources/images/doctorIcon.png
  src/main/resources/images/patientIcon.png
  src/main/resources/view/AppointmentListCard.fxml
Labels: priority.medium, type.task

#92 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddAppoiintmentActivityDiagram.puml
  docs/diagrams/AddAppointmentSequenceDiagram.puml
  docs/images/AddAppoiintmentActivityDiagram.png
  docs/images/AddAppointmentSequenceDiagram.png
Labels: priority.medium, type.task

#85 Delete appointment recursively
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
Labels: priority.low, type.task

#94 Update DG queryPatient and queryDoctor
  docs/DeveloperGuide.md
  docs/diagrams/QueryPersonActivityDiagram.puml
  docs/images/QueryPersonActivityDiagram.png
Labels: priority.high, type.task

#96 update dg for delete appointment page
  docs/DeveloperGuide.md
  docs/diagrams/DeleteAppointmentActivityDiagram.puml
  docs/images/DeleteAppointmentActivityDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/test/java/seedu/address/MainAppTest.java
Labels: priority.high
