Repository AY2324S2-CS2103T-T15-1/tp, pull requests merged in 2024-04, with the labels that each got.

#106 standardise error messages
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/QueryDoctorAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/QueryPatientAppointmentCommand.java
Labels: priority.high, type.task

#107 Implement edit patient doctor functionality
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high, type.task

#110 Fix appointment bug
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
Labels: priority.high

#118 Fix name constraints
  src/main/java/seedu/address/model/person/Name.java
  src/main/resources/view/AppointmentListCard.fxml
  src/test/java/seedu/address/model/person/NameTest.java
Labels: priority.high, type.task

#124 Update Storage to use medicli.json filename
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.high, type.task

#126 Add delete command into UG
  docs/UserGuide.md
Labels: priority.high, type.task

#123 add query commands to UG
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/findAlexDavidResultDoctor.png
  docs/images/findAlexDavidResultPatient.png
  docs/images/findAppointmentInitialDoctor.png
  docs/images/findAppointmentInitialPatient.png
  docs/images/findAppointmentResultDoctor.png
  docs/images/findAppointmentResultPatient.png
Labels: priority.high, type.task

#125 Update doctor command usage
  src/main/java/seedu/address/logic/commands/QueryDoctorCommand.java
Labels: priority.high, type.task

#111 Fix app not starting on early appointment
  docs/UserGuide.md
  docs/images/editAppointment.PNG
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/addressbookinvalid.json
  src/test/java/seedu/address/ui/AppointmentCardTest.java
Labels: priority.high

#136 Branch fix ug
  docs/images/editAppointment.png
Labels: priority.high, type.task

#137 Update UG
  docs/UserGuide.md
  docs/images/deleteApptFinalState.png
  docs/images/deleteApptInitialState.png
  docs/images/deletePatient.png
Labels: priority.high, type.task

#207 Fix typo in addpatient/adddoctor/delete success message
  src/main/java/seedu/address/logic/Messages.java
  src/test/java/seedu/address/logic/MessagesTest.java
Labels: fix.Must, bug.Code

#208 Bug fixes
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: fix.Must, bug.Code

#210 Debug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/StorageManager.java
Labels: fix.Must, bug.Code

#211 Fix UG Bugs
  docs/UserGuide.md
Labels: priority.high, fix.Must, bug.UG

#212 Add future enhancements section to DG
  docs/DeveloperGuide.md
Labels: priority.high, type.task

#228 Update user guide
  docs/UserGuide.md
Labels: priority.medium

#250 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddAppoiintmentActivityDiagram.puml
  docs/diagrams/AddPersonActivityDiagram.puml
  docs/diagrams/AppointmentClassDiagram.puml
  docs/diagrams/AppointmentObjectDiagram.puml
  docs/images/AddAppoiintmentActivityDiagram.png
  docs/images/AppointmentClassDiagram.png
  docs/images/AppointmentObjectDiagram.png
Labels: priority.high, type.task
